### ISSUE TITLE
C++23

### ISSUE THREAD

**Issue by reworks-org** [reworks-org/galaxy#146]
- [ ] Coroutine Support
    - [ ] C# style async/await
- [ ] <ranges> support.
- [ ] std::vector::contains

**Comment by DomRe** [comment]
Use of C++20 Ranges.

**Comment by DomRe** [comment]
See https://github.com/RandyGaul/cute_headers/blob/master/cute_coroutine.h for ideas.
Timer, StateMachine, Textbox, ThreadPool

https://www.modernescpp.com/index.php/c-20-thread-pools-with-cppcoro

https://gist.github.com/kennykerr/13082fbb4b6502fd7fa9570a896db4f0

https://en.cppreference.com/w/cpp/language/coroutines

https://www.google.com/search?client=firefox-b-d&ei=ixZWXs_uBOjWz7sPoOiwyAc&q=recycle+threads+in+threadpool
https://github.com/progschj/ThreadPool/blob/master/ThreadPool.h
https://thispointer.com/designing-a-thread-pool-framework-part-1-whats-the-need-of-a-thread-pool/

**Comment by reworks-org** [comment]
done
